name: Automerge Crowdin

on:
  workflow_dispatch:
  # At 02:00 (UTC) daily
  # https://crontab.guru/#0_2_*_*_*
  schedule:
    - cron: '0 2 * * *'

jobs:
  automerge-crowdin-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Generate Valora Actions Token
        id: valora-actions-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.VALORA_ACTIONS_APP_ID }}
          private-key: ${{ secrets.VALORA_ACTIONS_PRIVATE_KEY }}
      - uses: actions/checkout@v4
      - uses: actions/github-script@v7
        with:
          github-token: ${{ steps.valora-actions-token.outputs.token }}
          script: |
            const script = require('.github/scripts/automergeCrowdinPr.js')
            await script({github, context, core})
